### PR TITLE
Move theme demos to separate tab

### LINKED ISSUE #16: Improve demos
Examples could all have at least three layout items, to better illustrate the gap feature.

Also reduce the number of demos (combine features), no need to demonstrate every feature for horizontal/vertical layout separately. Or at least split the elements on different pages.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #16

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/21)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/demos.json, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/21#-L-WDPlcWv5gCR3uuR2d:-L-WDPlcWv5gCR3uuR2e:b-ww3nvu) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/30f5602d74ac7856b4b033d9ba270466651bead6/demo/demos.json#L14)):*
> ```JSON
>   },
>   {
>     "name": "Theme examples",
> ```

Misnamed?

It’s not quite that examples of theme are given there, but rather theme variants are listed there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/21)*

**Comment by web-padawan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/demos.json, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/21#-L-WDPlcWv5gCR3uuR2d:-L-WJ5LR2Ge8H4sd8V-G:b-896fix) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/30f5602d74ac7856b4b033d9ba270466651bead6/demo/demos.json#L14)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Misnamed?

It’s not quite that examples of theme are given there, but rather theme variants are listed there.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/21)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/21#-:-L-WJY3T1cDyR51fLY51:bnfp4nl)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[demo/ordered-layout-theme-demos.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/21#-L-WJr0H0S7jqM87WyEI:-L-WJr0H0S7jqM87WyEJ:b-tcqsij) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/5674687588df3ce8fa7676a87ad2ad015cf9ce66/demo/ordered-layout-theme-demos.html#L10)):*
> ```HTML
>     <h3>Layout Without Gaps</h3>
>     <p>
>       The <code>gap-none</code> theme can be applied to both horizontal and vertical layout.
> ```

Maybe `s/theme/theme variation/` here and below to further reduce confusion between Themes and Theme variants.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/21)*

**Comment by web-padawan** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/ordered-layout-theme-demos.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/21#-L-WJr0H0S7jqM87WyEI:-L-WNJn1lwWxwhVSz5G2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/5674687588df3ce8fa7676a87ad2ad015cf9ce66/demo/ordered-layout-theme-demos.html#L10)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe `s/theme/theme variation/` here and below to further reduce confusion between Themes and Theme variants.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/21)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/21)*

**Pull request merged**
