### PR TITLE
Add small/large spacing variations

### PR DESCRIPTION
**Pull request by heruan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/35)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Nice idea! @jouni wdyt?

**Comment by jouni** [comment]
Yeah, we’ve talked about this with @heruan before already, and it was the plan all along :)

Already looked at the PR, LGTM.

**Comment by YuriyVaadin** [comment]
Dear @heruan, thank you very much for your contribution!
Could you please rebase your branch on top of the current master as needed commits with test fixes are missing?

**Comment by heruan** [comment]
@YuriyVaadin done!

**Comment by web-padawan** [comment]
@heruan thank you for contributing! It would be nice to also mention these variations in demos. Not necessarily a separate demo for each variation, but some kind of comparison. Other than that, :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/35#-:-L1SP_jG03_WiV1BNDXL:brl0i4n)*

**Comment by heruan** [comment]
Comparison demo for spacing variations: done.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/35#-:-L1UEjZF_3HORjfm3vbN:b-nzfvqx)*

**Comment by YuriyVaadin** [comment]
Awesome job! Thank you very much for your work! :lgtm: 

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/35#-:-L1WG3ip0SeLGDB6fe6l:b-yg3whk)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/35)*

**Pull request merged**
