### PR TITLE
Adding theme/material

### PR DESCRIPTION
**Pull request by manolo**
Connected to vaadin/vaadin-material-styles#49

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/55)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/55#-LEOUZmWEsVJFx34h-ZJ:-LEOUZmWEsVJFx34h-ZK:b-d057h4) (no related file):*
Excess files:
https://github.com/vaadin/vaadin-ordered-layout/tree/md-preview/theme/material
vs
https://github.com/vaadin/vaadin-ordered-layout/tree/p3-preview/theme/lumo

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/55)*

**Comment by tomivirkki** [comment]
*[bower.json, line 33 at r1](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/55#-LEOV8cD9Y-jlkJdg2K3:-LEOV8cD9Y-jlkJdg2K4:b5d6kdi) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/8709f7ae17a580d47d9bb7f7896e448e9a32886d/bower.json#L33)):*
> ```JSON
>     "vaadin-lumo-styles": "vaadin/vaadin-lumo-styles#^1.0.0",
>     "vaadin-material-styles": "vaadin/vaadin-material-styles#^1.0.0",
>     "vaadin-material-styles": "vaadin/vaadin-material-styles#^1.0.0",
> ```

duplicate

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/55)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 33 at r1](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/55#-LEOV8cD9Y-jlkJdg2K3:-LEOf8NQ1OTUeeTG61H3:bd30ifx) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/8709f7ae17a580d47d9bb7f7896e448e9a32886d/bower.json#L33)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

duplicate
</blockquote></details>

good catch

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/55)*

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/55#-LEOUZmWEsVJFx34h-ZJ:-LEOgEvy9oWNuN8uaQJI:b-sjnmm4) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Excess files:
https://github.com/vaadin/vaadin-ordered-layout/tree/md-preview/theme/material
vs
https://github.com/vaadin/vaadin-ordered-layout/tree/p3-preview/theme/lumo
</blockquote></details>

Aligned with lumo

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/55)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/55#-:-LEOmJYZ6LACUwsVW_F-:bnfp4nl)*

**Pull request merged**
