### PR TITLE
Add gaps spacing support, CSS properties, theme variations

### LINKED ISSUE #3: Make it easy to add whitespace between the elements inside the layout (a.k.a. “spacing”)
For convenience, let’s consider adding attributes for defining the spacing between the elements in the layout.

For example:

```html
<!-- Add default spacing -->
<vaadin-vertical-layout spacing>
  ...
</vaadin-vertical-layout>

<!-- Set explicit spacing value -->
<vaadin-vertical-layout spacing="L">
  ...
</vaadin-vertical-layout>
```

The actual spacing sizes should be controllable with CSS/theme, e.g. 
```css
--vaadin-layout-spacing-xs: 4px;
--vaadin-layout-spacing-s: 8px;
--vaadin-layout-spacing-m: 16px;
--vaadin-layout-spacing-l: 32px;
--vaadin-layout-spacing-xl: 64px;
```

### LINKED ISSUE #5: Fix APIdocs
- [ ] APIdocs display properties and functions from Polymer.Element API

### PR DESCRIPTION
**Pull request by platosha**
Fixes #3
Fixes #5

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/8)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 24 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-vertical-layout.html, line 111 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-KytUmqBMxUc2Gc1XvUP:-KytUmqBMxUc2Gc1XvUQ:b1t6514) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/bfbfacc248dc6585d95e67cd36f4f8da4727ecdd/vaadin-vertical-layout.html#L111)):*
> ```HTML
>        * @demo demo/index.html
>        */
>       class VerticalLayoutElement extends Vaadin.ThemableMixin(Polymer.Element) {
> ```

The docs still list Polymer.Element APIs https://www.dropbox.com/s/b7it6ld2441f9v1/Screenshot%202017-11-14%2009.46.56.png?dl=0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8)*

**Comment by web-padawan** [comment]
Reviewed 24 of 24 files at r1.
Review status: 22 of 24 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-horizontal-layout.html, line 107 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-KytQe72oGpBHe3BSNWi:-KytQe72oGpBHe3BSNWj:b-q8cffx) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/322a5ee9bd7299fd31f8a84e6f8c4f19b894be09/vaadin-horizontal-layout.html#L107)):*
> ```HTML
>        *
>        * @memberof Vaadin
>        * @extends Vaadin.ThemableMixin
> ```

This JSDoc should be changed to `@mixes` for consistency with other elements

---

*[vaadin-vertical-layout.html, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-KytTK1pBbMTzclKTvn2:-KytTK1pBbMTzclKTvn3:b-5tiqz) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/322a5ee9bd7299fd31f8a84e6f8c4f19b894be09/vaadin-vertical-layout.html#L33)):*
> ```HTML
>           the layout itself.
>         */
>         margin-top: calc(-0.5 * var(--vaadin-vertical-layout-row-gap));
> ```

Why don't we use just `::slotted(:first-child)` and `::slotted(:last-child)` instead to reset margins? Apart from being more descriptive, that would make inspecting easier.

As of now, the height of inner `#layout`block  is bigger than the element itself when inspecting in dev tools, which might be confusing for someone not aware of this trick.

Not a blocker.

---

*[vaadin-vertical-layout.html, line 108 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-KytRL3KnQRnxk4L1RDz:-KytRL3KnQRnxk4L1RE-:bwz1gsk) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/322a5ee9bd7299fd31f8a84e6f8c4f19b894be09/vaadin-vertical-layout.html#L108)):*
> ```HTML
>        *
>        * @memberof Vaadin
>        * @extends Vaadin.ThemableMixin
> ```

Same as above, change to `@mixes` for consistency

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8)*

**Comment by tomivirkki** [comment]
The spacing is different in Chrome and Firefox https://www.dropbox.com/s/r1szktjtge2kk8s/Screenshot%202017-11-14%2009.52.52.png?dl=0

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-:-KytWDFDSDuXgMGLcWac:b-93rwa3)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-vertical-layout.html, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-KytTK1pBbMTzclKTvn2:-KytYxOmhO3L19Pu1Q15:bx4z8td) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/322a5ee9bd7299fd31f8a84e6f8c4f19b894be09/vaadin-vertical-layout.html#L33)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Why don't we use just `::slotted(:first-child)` and `::slotted(:last-child)` instead to reset margins? Apart from being more descriptive, that would make inspecting easier.

As of now, the height of inner `#layout`block  is bigger than the element itself when inspecting in dev tools, which might be confusing for someone not aware of this trick.

Not a blocker.
</blockquote></details>

UPD: my solution does not take `template` tags into account so it would break. It would be nice to have a test ensuring this doesn't happen now. 

BTW, a note about `<dom-if>` elements: these used to not have `display: none` until 2.1.0, which caused issues similar to described above. So maybe we should depend on ^2.1.0 in `bower.json`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8)*

**Comment by platosha** [comment]
Review status: 19 of 24 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-horizontal-layout.html, line 107 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-KytQe72oGpBHe3BSNWi:-KytfRK6uJXd_o09iA3c:b-896fix) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/322a5ee9bd7299fd31f8a84e6f8c4f19b894be09/vaadin-horizontal-layout.html#L107)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

This JSDoc should be changed to `@mixes` for consistency with other elements
</blockquote></details>

Done.

---

*[vaadin-vertical-layout.html, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-KytTK1pBbMTzclKTvn2:-Kytdywr-03lq7P1AzA9:bpjatz0) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/322a5ee9bd7299fd31f8a84e6f8c4f19b894be09/vaadin-vertical-layout.html#L33)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

UPD: my solution does not take `template` tags into account so it would break. It would be nice to have a test ensuring this doesn't happen now. 

BTW, a note about `<dom-if>` elements: these used to not have `display: none` until 2.1.0, which caused issues similar to described above. So maybe we should depend on ^2.1.0 in `bower.json`?
</blockquote></details>

There is a test for the negative margin, therefore this is already ensured.

I wouldn’t depend on `^2.1.0` for this reason alone. In case if someone bumps into this issue, it’s easy enough to notice the issue and workaround on `2.0` too.

---

*[vaadin-vertical-layout.html, line 108 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-KytRL3KnQRnxk4L1RDz:-KytfQTSxRbdnvCTwEQf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/322a5ee9bd7299fd31f8a84e6f8c4f19b894be09/vaadin-vertical-layout.html#L108)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Same as above, change to `@mixes` for consistency
</blockquote></details>

Done.

---

*[vaadin-vertical-layout.html, line 111 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-KytUmqBMxUc2Gc1XvUP:-KytfVJWjS14IENdjte5:b-896fix) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/bfbfacc248dc6585d95e67cd36f4f8da4727ecdd/vaadin-vertical-layout.html#L111)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The docs still list Polymer.Element APIs https://www.dropbox.com/s/b7it6ld2441f9v1/Screenshot%202017-11-14%2009.46.56.png?dl=0
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8)*

**Comment by web-padawan** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8)*

**Comment by platosha** [comment]
@tomivirkki fixed.

---

Review status: 23 of 25 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-:-KytmppcuGHrKlNpeJVu:b-ez8ixu)*

**Comment by tomivirkki** [comment]
The first demos look ok now but there still are differences: https://www.dropbox.com/s/kgt9rbr365f6imd/Screenshot%202017-11-14%2011.23.55.png?dl=0

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-:-Kytq315sjRLBv9pJI71:bbefi1f)*

**Comment by platosha** [comment]
@tomivirkki :see_no_evil: fixed.

---

Review status: 23 of 25 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-:-KyuITHYyE7uDFhHHRkJ:b-iqedzk)*

**Comment by tomivirkki** [comment]
Still looks different: https://www.dropbox.com/s/btco6i2l3fq8g4w/Screenshot%202017-11-14%2014.30.13.png?dl=0

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-:-KyuVf65YBnbawTGji5F:b-l6uh9m)*

**Comment by platosha** [comment]
@tomivirkki fixed (this time for real, I hope).

---

Review status: 23 of 25 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-:-KyuWBXXCDzFDam17Y3c:b24rgkq)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 18 of 24 files at r1, 5 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-:-KyuxSh9krb9RxDU34yZ:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 18 of 24 files at r1, 5 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/8#-:-KyyG-LgEJLY3fXiB_kd:bnfp4nl)*

**Pull request merged**
