### PR TITLE
Fix "main" in bower.json

### LINKED ISSUE #18: Fix "main" in bower.json
List both vaadin-vertical-layout.html & vaadin-horizontal-layout.html

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #18

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/22)

### CODE REVIEW

**Comment by web-padawan** [comment]
tip: you can include `[skip ci]` in your commit message to skip Travis for the commit and PR

BTW, I personally recommend making shorter commit messages where possible. E. g. in this case the only file affected by your commit is `bower.json`, so no need to mention it, something simpler would be also fine.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/22#-L-VolzzJ80XYyRfvfmc:-L-VolzzJ80XYyRfvfmd:bdegkvu) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/09de1efecc1da533cbc1ca67fe404732291e10d1/bower.json#L8)):*
> ```JSON
>   ],
>   "description": "vaadin-ordered-layout",
>   "main": ["vaadin-horizontal-layout.html", "vaadin-vertical-layout.html"],
> ```

let's follow the code style used in the `keywords` below. So please split this into separate lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/22#-:-L-Vp2ObdN6FjZ6MabJH:b-vm5517)*

**Comment by vicsstar** [comment]
Cool tip! Thanks. :sweat_smile: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/22#-:-L-W12iUMkpXI46JoXyF:bou18s)*

**Comment by vicsstar** [comment]
*[bower.json, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/22#-L-VolzzJ80XYyRfvfmc:-L-W24t3MxS_3HF_mYw0:b-896fix) ([raw file](https://github.com/vaadin/vaadin-ordered-layout/blob/09de1efecc1da533cbc1ca67fe404732291e10d1/bower.json#L8)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

let's follow the code style used in the `keywords` below. So please split this into separate lines
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/22)*

**Comment by web-padawan** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/22#-:-L-W4zUrc0Hefzfn4STC:b-uwkowd)*

**Pull request merged**
