### PR TITLE
Implement Valo theme

### PR DESCRIPTION
**Pull request by web-padawan**
Connected to vaadin/components-team-tasks#298

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/33)

### CODE REVIEW

**Comment by heruan** [comment]
Large and small `spacing` variants would be very useful to start with.

**Comment by web-padawan** [comment]
@jouni WDYT about this suggestion? If we'd like to have it supported, let's open another issue so it could be targeted by a separate PR.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/33#-:-L0iXAv_5EAqtSvBgVFc:bmz5v1a)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/33#-:-L0j6zoBq7UPkGWOWN1g:bnfp4nl)*

**Comment by jouni** [comment]
@heruan and @web-padawan: yeah, those should be added before the first beta.

**Comment by web-padawan** [comment]
Reviewed 1 of 13 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/33)*

**Comment by jouni** [comment]
:lgtm:

---

Reviewed 9 of 13 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/33#-:-L0p17AswAXRQ6v9sLWu:bnfp4nl)*

**Comment by web-padawan** [comment]
Some tests checking `rem` values are still broken, I will fix these tomorrow on master branch.

**Pull request merged**
