### PR TITLE
Make host a flex container, remove CSS API for gaps

### LINKED ISSUE #30: Prototype new structure for ordered layout
__Why__: the current implementation with the nested flex container does not quite meet the Flow team expectations and API requirements.

__What__:

- return back to the initial structure (host element is a flex container)
- drop custom CSS property fort gap
  - there should be no gap by default
  - user can apply gaps specified by theme
  - for custom gaps, CSS `margin` can be still used

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #30

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout/31)

### CODE REVIEW

**Comment by jouni** [comment]
So no default gap implementation? 

Also, we should drop auto-flexing of the child elements.

**Comment by jouni** [comment]
If this is a prototype, do we want to merge it to master?

**Comment by jouni** [comment]
Also, the `_justifyContent` and `_alignItems` properties were added only because there was the internal `#layout` element. Now when it is removed, no need to keep those JS properties, right?

**Comment by web-padawan** [comment]
@jouni what the gap amount should be? Is it ok if we add the `theme="spacing"´for now which would set margin between items to e. g. `1em`?

Removed the `_justifyContent ` and `_alignItems ` properties.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/31#-:-L0FDFXt9Mr2aGx0eabC:b-gn9dou)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r1, 17 of 17 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/31#-:-L0KAmpZw7UhhRP_jMuz:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/31)*

**Comment by web-padawan** [comment]
@tomivirkki I think this is now ready for another review. Added tests to address outside space issue. Actually, the pseudo element negative margin is also tested but let's maybe keep both of these for now to be more explicit.

---

Review status: 13 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/31#-:-L0OP-xZERLErFZ0DLhq:b-vb7hd5)*

**Comment by tomivirkki** [comment]
Reviewed 5 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout/31)*

**Pull request merged**
